site_name: Documentación mysitename
dev_addr: "0.0.0.0:8080"
nav:
  - Inicio: index.md
  - Local: local.md
  - Git: Git.md
  - Tests: tests.md
  - Otros:
      - Wodby: otros/README-wodby.md
      - Docker4drupal: otros/README-docker4drupal.md
      - MkDocs: otros/mkdocs.md
      - Composer Drupal project: otros/composer-drupal-project.md
markdown_extensions:
  - admonition
theme:
  name: material
  language: es
  logo: ./assets/favicon.ico
