name: Makefile CI

on:
  push:
    branches: [ "ci" ]
  pull_request:
    branches: [ "ci" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: docker-practice/actions-setup-docker@master
      timeout-minutes: 12

    - uses: actions/checkout@v3

    - name: test docker
      run: docker
