name: Makefile CI

on:
  push:
    branches: [ "ci" ]
  pull_request:
    branches: [ "ci" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: setup
      run: make setup

    - name: onboard
      run: make onboard

    - name: install
      run: make install
