name: Test docker proyect in macos

on:
    push:
        branches:
            - ci

concurrency:
    group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
    cancel-in-progress: true

permissions:
    contents: read

jobs:
    test-macos:
        name: Test docker proyect in macos
        runs-on: macos-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Test docker proyect in macos
              uses: docker://docker:20.10.7
              with:
                  args: |
                      make
