name: OS CHECKER

on:
  push:
    branches: [ "ci" ]
  pull_request:
    branches: [ "ci" ]


jobs:
  os_checker:

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - name: setup-docker
      uses: docker-practice/actions-setup-docker@master
      timeout-minutes: 12

    - name: checkout
      uses: actions/checkout@v3

    - name: test docker
      run: docker

    - name: test make
      run: make
