name: Makefile CI

on:
  push:
    branches: [ "ci" ]
  pull_request:
    branches: [ "ci" ]


jobs:
  os_checker:
    strategy:
      matrix:
        version: [10, 12, 14]
        os: [ubuntu-latest, windows-latest, macos-latest, linux-latest]
    steps:
    - uses: docker-practice/actions-setup-docker@master
      timeout-minutes: 12

    - uses: actions/checkout@v3

    - name: test docker
      run: docker
